### PR TITLE
Refactor range info

### PR DESCRIPTION
**Pull request by vadymmarkov**
# Why?

To make it easier to configure range sliders and steppers.

# What?

- Rename `RangeFilterInfo` to `RangeFilterConfiguration` and combined it with `StepSliderInfo`
- Introduce `StepperFilterConfiguration` as a separate configuration type for stepper
- Update filter configuration to use new types
- Use `RangeFilterConfiguration` and `StepperFilterConfiguration` as a part of filter kind. It makes it more predictable when it comes to creation of range and stepper view controllers, because we don't display filters not configured to be ranges or steppers.

# Show me

No UI changes

### CODE REVIEW

**Comment by shredlocker** [comment]
Is there a way to handle the mutually exclusive filter without using the `FilterConfiguration`? I seems like that is the only place we use the config after these changes. It would be nice to remove the config from `CharcoalViewController` and `RootFilterViewController`

**Comment by vadymmarkov** [comment]
We can potentially create `RootFilterViewController` with `mutuallyExclusiveFilters: Set<String>` instead of `config`. In `CharcoalViewController we can still keep `config` in init method, but store only `mutuallyExclusiveFilters` to local var. What do you think?

**Comment by shredlocker** [comment]
Sounds good for now ;)

**Comment by shredlocker** [comment]
Or, add `root` in `Filter.Kind` with the mutually exclusive filters

**Comment by shredlocker** [comment]
I think this looks good! Good job 😄

**Pull request merged**
